// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/airpurifier/v1/airpurifier.proto

package airpurifierpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentAirPurifierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentAirPurifierRequest) Reset() {
	*x = GetCurrentAirPurifierRequest{}
	mi := &file_proto_airpurifier_v1_airpurifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentAirPurifierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentAirPurifierRequest) ProtoMessage() {}

func (x *GetCurrentAirPurifierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_airpurifier_v1_airpurifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentAirPurifierRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentAirPurifierRequest) Descriptor() ([]byte, []int) {
	return file_proto_airpurifier_v1_airpurifier_proto_rawDescGZIP(), []int{0}
}

type GetCurrentAirPurifierResponse struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	Power               string                  `protobuf:"bytes,1,opt,name=power,proto3" json:"power,omitempty"`
	IsOn                bool                    `protobuf:"varint,2,opt,name=is_on,json=isOn,proto3" json:"is_on,omitempty"`
	Aqi                 int32                   `protobuf:"varint,3,opt,name=aqi,proto3" json:"aqi,omitempty"`
	AverageAqi          int32                   `protobuf:"varint,4,opt,name=average_aqi,json=averageAqi,proto3" json:"average_aqi,omitempty"`
	Humidity            int32                   `protobuf:"varint,5,opt,name=humidity,proto3" json:"humidity,omitempty"`
	TemperatureC        *wrapperspb.DoubleValue `protobuf:"bytes,6,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"`
	Mode                string                  `protobuf:"bytes,7,opt,name=mode,proto3" json:"mode,omitempty"`
	FavoriteLevel       int32                   `protobuf:"varint,8,opt,name=favorite_level,json=favoriteLevel,proto3" json:"favorite_level,omitempty"`
	FilterLifeRemaining int32                   `protobuf:"varint,9,opt,name=filter_life_remaining,json=filterLifeRemaining,proto3" json:"filter_life_remaining,omitempty"`
	FilterHoursUsed     int32                   `protobuf:"varint,10,opt,name=filter_hours_used,json=filterHoursUsed,proto3" json:"filter_hours_used,omitempty"`
	MotorSpeed          int32                   `protobuf:"varint,11,opt,name=motor_speed,json=motorSpeed,proto3" json:"motor_speed,omitempty"`
	PurifyVolume        int32                   `protobuf:"varint,12,opt,name=purify_volume,json=purifyVolume,proto3" json:"purify_volume,omitempty"`
	Led                 bool                    `protobuf:"varint,13,opt,name=led,proto3" json:"led,omitempty"`
	LedBrightness       *wrapperspb.Int32Value  `protobuf:"bytes,14,opt,name=led_brightness,json=ledBrightness,proto3" json:"led_brightness,omitempty"`
	Buzzer              *wrapperspb.BoolValue   `protobuf:"bytes,15,opt,name=buzzer,proto3" json:"buzzer,omitempty"`
	ChildLock           bool                    `protobuf:"varint,16,opt,name=child_lock,json=childLock,proto3" json:"child_lock,omitempty"`
	MeasuredAtUnixMs    int64                   `protobuf:"varint,17,opt,name=measured_at_unix_ms,json=measuredAtUnixMs,proto3" json:"measured_at_unix_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetCurrentAirPurifierResponse) Reset() {
	*x = GetCurrentAirPurifierResponse{}
	mi := &file_proto_airpurifier_v1_airpurifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentAirPurifierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentAirPurifierResponse) ProtoMessage() {}

func (x *GetCurrentAirPurifierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_airpurifier_v1_airpurifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentAirPurifierResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentAirPurifierResponse) Descriptor() ([]byte, []int) {
	return file_proto_airpurifier_v1_airpurifier_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentAirPurifierResponse) GetPower() string {
	if x != nil {
		return x.Power
	}
	return ""
}

func (x *GetCurrentAirPurifierResponse) GetIsOn() bool {
	if x != nil {
		return x.IsOn
	}
	return false
}

func (x *GetCurrentAirPurifierResponse) GetAqi() int32 {
	if x != nil {
		return x.Aqi
	}
	return 0
}

func (x *GetCurrentAirPurifierResponse) GetAverageAqi() int32 {
	if x != nil {
		return x.AverageAqi
	}
	return 0
}

func (x *GetCurrentAirPurifierResponse) GetHumidity() int32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *GetCurrentAirPurifierResponse) GetTemperatureC() *wrapperspb.DoubleValue {
	if x != nil {
		return x.TemperatureC
	}
	return nil
}

func (x *GetCurrentAirPurifierResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GetCurrentAirPurifierResponse) GetFavoriteLevel() int32 {
	if x != nil {
		return x.FavoriteLevel
	}
	return 0
}

func (x *GetCurrentAirPurifierResponse) GetFilterLifeRemaining() int32 {
	if x != nil {
		return x.FilterLifeRemaining
	}
	return 0
}

func (x *GetCurrentAirPurifierResponse) GetFilterHoursUsed() int32 {
	if x != nil {
		return x.FilterHoursUsed
	}
	return 0
}

func (x *GetCurrentAirPurifierResponse) GetMotorSpeed() int32 {
	if x != nil {
		return x.MotorSpeed
	}
	return 0
}

func (x *GetCurrentAirPurifierResponse) GetPurifyVolume() int32 {
	if x != nil {
		return x.PurifyVolume
	}
	return 0
}

func (x *GetCurrentAirPurifierResponse) GetLed() bool {
	if x != nil {
		return x.Led
	}
	return false
}

func (x *GetCurrentAirPurifierResponse) GetLedBrightness() *wrapperspb.Int32Value {
	if x != nil {
		return x.LedBrightness
	}
	return nil
}

func (x *GetCurrentAirPurifierResponse) GetBuzzer() *wrapperspb.BoolValue {
	if x != nil {
		return x.Buzzer
	}
	return nil
}

func (x *GetCurrentAirPurifierResponse) GetChildLock() bool {
	if x != nil {
		return x.ChildLock
	}
	return false
}

func (x *GetCurrentAirPurifierResponse) GetMeasuredAtUnixMs() int64 {
	if x != nil {
		return x.MeasuredAtUnixMs
	}
	return 0
}

type SetAirPurifierPowerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	On            bool                   `protobuf:"varint,1,opt,name=on,proto3" json:"on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAirPurifierPowerRequest) Reset() {
	*x = SetAirPurifierPowerRequest{}
	mi := &file_proto_airpurifier_v1_airpurifier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAirPurifierPowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAirPurifierPowerRequest) ProtoMessage() {}

func (x *SetAirPurifierPowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_airpurifier_v1_airpurifier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAirPurifierPowerRequest.ProtoReflect.Descriptor instead.
func (*SetAirPurifierPowerRequest) Descriptor() ([]byte, []int) {
	return file_proto_airpurifier_v1_airpurifier_proto_rawDescGZIP(), []int{2}
}

func (x *SetAirPurifierPowerRequest) GetOn() bool {
	if x != nil {
		return x.On
	}
	return false
}

type SetAirPurifierModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAirPurifierModeRequest) Reset() {
	*x = SetAirPurifierModeRequest{}
	mi := &file_proto_airpurifier_v1_airpurifier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAirPurifierModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAirPurifierModeRequest) ProtoMessage() {}

func (x *SetAirPurifierModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_airpurifier_v1_airpurifier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAirPurifierModeRequest.ProtoReflect.Descriptor instead.
func (*SetAirPurifierModeRequest) Descriptor() ([]byte, []int) {
	return file_proto_airpurifier_v1_airpurifier_proto_rawDescGZIP(), []int{3}
}

func (x *SetAirPurifierModeRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type SetAirPurifierFavoriteLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAirPurifierFavoriteLevelRequest) Reset() {
	*x = SetAirPurifierFavoriteLevelRequest{}
	mi := &file_proto_airpurifier_v1_airpurifier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAirPurifierFavoriteLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAirPurifierFavoriteLevelRequest) ProtoMessage() {}

func (x *SetAirPurifierFavoriteLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_airpurifier_v1_airpurifier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAirPurifierFavoriteLevelRequest.ProtoReflect.Descriptor instead.
func (*SetAirPurifierFavoriteLevelRequest) Descriptor() ([]byte, []int) {
	return file_proto_airpurifier_v1_airpurifier_proto_rawDescGZIP(), []int{4}
}

func (x *SetAirPurifierFavoriteLevelRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type SetAirPurifierControlResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Current       *GetCurrentAirPurifierResponse `protobuf:"bytes,1,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAirPurifierControlResponse) Reset() {
	*x = SetAirPurifierControlResponse{}
	mi := &file_proto_airpurifier_v1_airpurifier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAirPurifierControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAirPurifierControlResponse) ProtoMessage() {}

func (x *SetAirPurifierControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_airpurifier_v1_airpurifier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAirPurifierControlResponse.ProtoReflect.Descriptor instead.
func (*SetAirPurifierControlResponse) Descriptor() ([]byte, []int) {
	return file_proto_airpurifier_v1_airpurifier_proto_rawDescGZIP(), []int{5}
}

func (x *SetAirPurifierControlResponse) GetCurrent() *GetCurrentAirPurifierResponse {
	if x != nil {
		return x.Current
	}
	return nil
}

var File_proto_airpurifier_v1_airpurifier_proto protoreflect.FileDescriptor

const file_proto_airpurifier_v1_airpurifier_proto_rawDesc = "" +
	"\n" +
	"&proto/airpurifier/v1/airpurifier.proto\x12\x0eairpurifier.v1\x1a\x1egoogle/protobuf/wrappers.proto\"\x1e\n" +
	"\x1cGetCurrentAirPurifierRequest\"\x95\x05\n" +
	"\x1dGetCurrentAirPurifierResponse\x12\x14\n" +
	"\x05power\x18\x01 \x01(\tR\x05power\x12\x13\n" +
	"\x05is_on\x18\x02 \x01(\bR\x04isOn\x12\x10\n" +
	"\x03aqi\x18\x03 \x01(\x05R\x03aqi\x12\x1f\n" +
	"\vaverage_aqi\x18\x04 \x01(\x05R\n" +
	"averageAqi\x12\x1a\n" +
	"\bhumidity\x18\x05 \x01(\x05R\bhumidity\x12A\n" +
	"\rtemperature_c\x18\x06 \x01(\v2\x1c.google.protobuf.DoubleValueR\ftemperatureC\x12\x12\n" +
	"\x04mode\x18\a \x01(\tR\x04mode\x12%\n" +
	"\x0efavorite_level\x18\b \x01(\x05R\rfavoriteLevel\x122\n" +
	"\x15filter_life_remaining\x18\t \x01(\x05R\x13filterLifeRemaining\x12*\n" +
	"\x11filter_hours_used\x18\n" +
	" \x01(\x05R\x0ffilterHoursUsed\x12\x1f\n" +
	"\vmotor_speed\x18\v \x01(\x05R\n" +
	"motorSpeed\x12#\n" +
	"\rpurify_volume\x18\f \x01(\x05R\fpurifyVolume\x12\x10\n" +
	"\x03led\x18\r \x01(\bR\x03led\x12B\n" +
	"\x0eled_brightness\x18\x0e \x01(\v2\x1b.google.protobuf.Int32ValueR\rledBrightness\x122\n" +
	"\x06buzzer\x18\x0f \x01(\v2\x1a.google.protobuf.BoolValueR\x06buzzer\x12\x1d\n" +
	"\n" +
	"child_lock\x18\x10 \x01(\bR\tchildLock\x12-\n" +
	"\x13measured_at_unix_ms\x18\x11 \x01(\x03R\x10measuredAtUnixMs\",\n" +
	"\x1aSetAirPurifierPowerRequest\x12\x0e\n" +
	"\x02on\x18\x01 \x01(\bR\x02on\"/\n" +
	"\x19SetAirPurifierModeRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\":\n" +
	"\"SetAirPurifierFavoriteLevelRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\"h\n" +
	"\x1dSetAirPurifierControlResponse\x12G\n" +
	"\acurrent\x18\x01 \x01(\v2-.airpurifier.v1.GetCurrentAirPurifierResponseR\acurrent2\xef\x03\n" +
	"\x12AirPurifierService\x12t\n" +
	"\x15GetCurrentAirPurifier\x12,.airpurifier.v1.GetCurrentAirPurifierRequest\x1a-.airpurifier.v1.GetCurrentAirPurifierResponse\x12p\n" +
	"\x13SetAirPurifierPower\x12*.airpurifier.v1.SetAirPurifierPowerRequest\x1a-.airpurifier.v1.SetAirPurifierControlResponse\x12n\n" +
	"\x12SetAirPurifierMode\x12).airpurifier.v1.SetAirPurifierModeRequest\x1a-.airpurifier.v1.SetAirPurifierControlResponse\x12\x80\x01\n" +
	"\x1bSetAirPurifierFavoriteLevel\x122.airpurifier.v1.SetAirPurifierFavoriteLevelRequest\x1a-.airpurifier.v1.SetAirPurifierControlResponseBEZCeco-knock-be-embedded/internal/grpc/pb/airpurifier/v1;airpurifierpbb\x06proto3"

var (
	file_proto_airpurifier_v1_airpurifier_proto_rawDescOnce sync.Once
	file_proto_airpurifier_v1_airpurifier_proto_rawDescData []byte
)

func file_proto_airpurifier_v1_airpurifier_proto_rawDescGZIP() []byte {
	file_proto_airpurifier_v1_airpurifier_proto_rawDescOnce.Do(func() {
		file_proto_airpurifier_v1_airpurifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_airpurifier_v1_airpurifier_proto_rawDesc), len(file_proto_airpurifier_v1_airpurifier_proto_rawDesc)))
	})
	return file_proto_airpurifier_v1_airpurifier_proto_rawDescData
}

var file_proto_airpurifier_v1_airpurifier_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_airpurifier_v1_airpurifier_proto_goTypes = []any{
	(*GetCurrentAirPurifierRequest)(nil),       // 0: airpurifier.v1.GetCurrentAirPurifierRequest
	(*GetCurrentAirPurifierResponse)(nil),      // 1: airpurifier.v1.GetCurrentAirPurifierResponse
	(*SetAirPurifierPowerRequest)(nil),         // 2: airpurifier.v1.SetAirPurifierPowerRequest
	(*SetAirPurifierModeRequest)(nil),          // 3: airpurifier.v1.SetAirPurifierModeRequest
	(*SetAirPurifierFavoriteLevelRequest)(nil), // 4: airpurifier.v1.SetAirPurifierFavoriteLevelRequest
	(*SetAirPurifierControlResponse)(nil),      // 5: airpurifier.v1.SetAirPurifierControlResponse
	(*wrapperspb.DoubleValue)(nil),             // 6: google.protobuf.DoubleValue
	(*wrapperspb.Int32Value)(nil),              // 7: google.protobuf.Int32Value
	(*wrapperspb.BoolValue)(nil),               // 8: google.protobuf.BoolValue
}
var file_proto_airpurifier_v1_airpurifier_proto_depIdxs = []int32{
	6, // 0: airpurifier.v1.GetCurrentAirPurifierResponse.temperature_c:type_name -> google.protobuf.DoubleValue
	7, // 1: airpurifier.v1.GetCurrentAirPurifierResponse.led_brightness:type_name -> google.protobuf.Int32Value
	8, // 2: airpurifier.v1.GetCurrentAirPurifierResponse.buzzer:type_name -> google.protobuf.BoolValue
	1, // 3: airpurifier.v1.SetAirPurifierControlResponse.current:type_name -> airpurifier.v1.GetCurrentAirPurifierResponse
	0, // 4: airpurifier.v1.AirPurifierService.GetCurrentAirPurifier:input_type -> airpurifier.v1.GetCurrentAirPurifierRequest
	2, // 5: airpurifier.v1.AirPurifierService.SetAirPurifierPower:input_type -> airpurifier.v1.SetAirPurifierPowerRequest
	3, // 6: airpurifier.v1.AirPurifierService.SetAirPurifierMode:input_type -> airpurifier.v1.SetAirPurifierModeRequest
	4, // 7: airpurifier.v1.AirPurifierService.SetAirPurifierFavoriteLevel:input_type -> airpurifier.v1.SetAirPurifierFavoriteLevelRequest
	1, // 8: airpurifier.v1.AirPurifierService.GetCurrentAirPurifier:output_type -> airpurifier.v1.GetCurrentAirPurifierResponse
	5, // 9: airpurifier.v1.AirPurifierService.SetAirPurifierPower:output_type -> airpurifier.v1.SetAirPurifierControlResponse
	5, // 10: airpurifier.v1.AirPurifierService.SetAirPurifierMode:output_type -> airpurifier.v1.SetAirPurifierControlResponse
	5, // 11: airpurifier.v1.AirPurifierService.SetAirPurifierFavoriteLevel:output_type -> airpurifier.v1.SetAirPurifierControlResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_airpurifier_v1_airpurifier_proto_init() }
func file_proto_airpurifier_v1_airpurifier_proto_init() {
	if File_proto_airpurifier_v1_airpurifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_airpurifier_v1_airpurifier_proto_rawDesc), len(file_proto_airpurifier_v1_airpurifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_airpurifier_v1_airpurifier_proto_goTypes,
		DependencyIndexes: file_proto_airpurifier_v1_airpurifier_proto_depIdxs,
		MessageInfos:      file_proto_airpurifier_v1_airpurifier_proto_msgTypes,
	}.Build()
	File_proto_airpurifier_v1_airpurifier_proto = out.File
	file_proto_airpurifier_v1_airpurifier_proto_goTypes = nil
	file_proto_airpurifier_v1_airpurifier_proto_depIdxs = nil
}
